spring:
  application:
    name: quickurl
  docker.compose.lifecycle-management: start_only
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 60000  # 60초
      cache-null-values: false
    cache-names:
      - urlCache

logging:
  level:
    dev.haisia.quickurl: DEBUG
    org.springframework.scheduling: INFO

# Rate Limit 설정
rate-limit:
  enabled: true
  request-limit: 10  # 기간당 최대 요청 수
  refill-duration-seconds: 1  # 리필 기간 (초)
  excluded-paths:
    - /favicon.ico
    - /actuator
    - /error
jwt:
  secret: thisisjwttokensecretkeythisisjwttokensecretkeythisisjwttokensecretkeythisisjwttokensecretkey
  access-token:
    validity-second: 3600
  refresh-token:
    validity-second: 86400