spring:
  application:
    name: quickurl
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 60000  # 60초
      cache-null-values: false
    cache-names:
      - urlCache

logging:
  level:
    dev.haisia.quickurl: INFO
    org.springframework.scheduling: INFO

# Swagger 설정 (프로덕션에서는 비활성화)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Rate Limit 설정
rate-limit:
  enabled: true
  request-limit: 10  # 기간당 최대 요청 수
  refill-duration-seconds: 1  # 리필 기간 (초)
  excluded-paths:
    - /favicon.ico
    - /actuator
    - /error
jwt:
  secret: ${JWT_SECRET}
  access-token:
    validity-second: 3600
  refresh-token:
    validity-second: 86400


app:
  base-url: ${APP_BASE_URL:https://quickurl.haisia.dev}
  cookie:
    secure: true
    domain: quickurl.haisia.dev
    same-site: Strict
    access-token-max-age: 3600
    refresh-token-max-age: 604800
  security:
    referer-check:
      enabled: ${REFERER_CHECK_ENABLED:true}
      allowed-domains:
        - ${APP_BASE_URL:https://quickurl.haisia.dev}
      allow-subdomains: false
      protected-paths:
        - /api/v1

brevo:
  api-key: ${SMTP_BREVO_API_KEY}
  api-base-url: ${SMTP_BREVO_BASE_URL}

# 클릭 로그 ip 수집
server:
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
  forward-headers-strategy: framework