spring:
  application:
    name: quickurl
  docker.compose.lifecycle-management: start_only
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 60000  # 60초
      cache-null-values: false
    cache-names:
      - urlCache

logging:
  level:
    dev.haisia.quickurl: DEBUG
    org.springframework.scheduling: INFO

# Swagger 설정
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Rate Limit 설정
rate-limit:
  enabled: true
  request-limit: 10  # 기간당 최대 요청 수
  refill-duration-seconds: 1  # 리필 기간 (초)
  excluded-paths:
    - /favicon.ico
    - /actuator
    - /error
jwt:
  secret: thisisjwttokensecretkeythisisjwttokensecretkeythisisjwttokensecretkeythisisjwttokensecretkey
  access-token:
    validity-second: 3600
  refresh-token:
    validity-second: 86400

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  cookie:
    secure: false
    domain: null
    same-site: Strict
    access-token-max-age: 3600
    refresh-token-max-age: 604800
  security:
    referer-check:
      enabled: ${REFERER_CHECK_ENABLED:false}
      allowed-domains:
        - ${APP_BASE_URL:http://localhost:8080}
      allow-subdomains: false
      protected-paths:
        - /api/v1
  email:
    send:
      enabled: ${EMAIL_SEND_ENABLED:false}

brevo:
  api-key: ${SMTP_BREVO_API_KEY:testApiKey}
  api-base-url: ${SMTP_BREVO_BASE_URL:testBaseURL}